name: Python Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Allure CLI
      run: |
        sudo apt update
        sudo apt install -y openjdk-11-jdk wget unzip
        wget https://github.com/allure-framework/allure2/releases/download/2.25.2/allure-2.25.2.zip -O allure.zip
        unzip allure.zip -d /opt/
        rm allure.zip
        sudo ln -s /opt/allure-2.25.2/bin/allure /usr/bin/allure

    - name: Run tests with Allure
      run: |
        pytest --alluredir=allure-results

    - name: Generate Allure report
      run: |
        allure generate allure-results --clean -o allure-report

    - name: Upload Allure report artifact
      uses: actions/upload-artifact@v4
      with:
        name: allure-report
        path: allure-report
