name: Run Pytest with Allure

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Allure
      run: |
        wget https://github.com/allure-framework/allure2/releases/download/2.28.0/allure-2.28.0.zip
        unzip allure-2.28.0.zip -d /opt/
        export PATH=$PATH:/opt/allure-2.28.0/bin
        allure --version

    - name: Run tests with Allure
      run: |
        pytest --alluredir=allure-results

    - name: Generate Allure Report
      run: |
        /opt/allure-2.28.0/bin/allure generate allure-results --clean -o allure-report

    - name: Upload Allure Report Artifact
      uses: actions/upload-artifact@v4
      with:
        name: allure-report
        path: allure-report
